DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    picture TEXT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(8) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);